export const bookList = [
  {
    title: "The Fault in our Stars",
    author: "me",
    readTime: "15",
    reads: "100",
    imagePath: "/images/3.png",
    owned: true,
  },
  {
    title: "The Fault in our Stars",
    author: "me",
    readTime: "15",
    reads: "100",
    imagePath: "/images/3.png",
    owned: true,
  },
  {
    title: "The Fault in our Stars",
    author: "me",
    readTime: "15",
    reads: "100",
    imagePath: "/images/3.png",
    owned: true,
  },
  {
    title: "The Fault in our Stars",
    author: "me",
    readTime: "15",
    reads: "100",
    imagePath: "/images/3.png",
    owned: true,
  },
  {
    title: "The Fault in our Stars",
    author: "me",
    readTime: "15",
    reads: "100",
    imagePath: "/images/3.png",
    owned: true,
  },
  {
    title: "The Fault in our Stars",
    author: "me",
    readTime: "15",
    reads: "100",
    imagePath: "/images/3.png",
    owned: true,
  },
  {
    title: "The Fault in our Stars",
    author: "me",
    readTime: "15",
    reads: "100",
    imagePath: "/images/3.png",
    owned: true,
  },
];

export const title = "Trending Blinks";
